FROM fedora:41

RUN dnf -y install make gcc gcc-c++ cmake git awk zip tar findutils which \
    mingw64-qt6-qtbase mingw64-qt6-qtmultimedia mingw64-gcc \
    mingw64-gcc-c++ qt6-qtmultimedia-devel qt6-qtbase-devel \
    mingw64-libarchive mingw64-sqlite mingw64-binutils

WORKDIR /work
